---
- name: Provisioning VirtualBox guest host (Controller) using Vagrant
  hosts: all
  serial: 1
  roles:
    - docker
    - docker-consul
    - consul-registrator
    - docker-mysql
    - docker-flask

