---
- name: add docker repository key into apt
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: add docker repository into apt
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
    update_cache: yes

- name: install docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
    install_recommends: no

- name: add user to docker group
  user:
    name: ubuntu
    groups: docker

- name: remove useless packages from the cache
  apt:
    autoclean: yes

- name: remove dependencies that are no longer required
  apt:
    autoremove: yes

