---
- name: create consul-registrator container
  docker_container:
    name: consul-registrator
    hostname: consul-registrator
    image: "gliderlabs/registrator:latest"
    state: started
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: ["consul://10.0.2.15:8500"]

- name: add consul-registrator container to inventory
  add_host:
    name: consul-registrator
    ansible_hostname: consul-registrator
    ansible_connection: docker
  changed_when: False

